Enable double precision tests. Added pid and tests
manchester-hyperloop/Dynamic_Pod_Control_Unit pull request #1
Opened 2020-11-17 21:34 UTC by mblenczewski

Please check

2020-11-17 21:54 UTC, manchester-hyperloop requested changes
Minor changes required. Some files are also in incorrect location.

2020-11-17 21:54 UTC, manchester-hyperloop commented on include/Core/Pid.hpp
> +        double next(const double source, const __time_t current_time_us)
Function should be implemented in .cpp file in src

2020-11-17 21:54 UTC, manchester-hyperloop commented on include/Core/Pid.hpp
> +#ifndef CORE_PID_HPP
File should have path include/Dynamics/Pid.hpp

2020-11-17 21:54 UTC, manchester-hyperloop commented on src/main.cpp
> +  }
PID calls shouldn't be made here. Remove this.

2020-11-17 21:54 UTC, manchester-hyperloop commented on src/main.cpp
> +
These variables shouldn't be defined here. Remove these.

2020-11-17 21:54 UTC, manchester-hyperloop commented on src/main.cpp
> +#include "Core/Pid.hpp"
Will not be used here in future. Remove this

2020-11-17 21:54 UTC, manchester-hyperloop commented on src/main.cpp
> +Core::Pid pid = Core::Pid(pid_setpoint, kp, ki, kd);
These variables should not be defined here. Remove these.

2020-11-17 21:54 UTC, manchester-hyperloop commented on test/Pid_Test/Pid_Test.cpp
> +void test_pid_works(void)
Requires comment for which specification this test meets

2020-11-17 21:54 UTC, manchester-hyperloop commented on test/Pid_Test/Pid_Test.cpp
> +void test_pid_getters_and_setters(void)
Requires comment for which specification this test meets

2020-11-17 21:54 UTC, manchester-hyperloop commented on test/Pid_Test/Pid_Test.cpp
> +    TEST_ASSERT_EQUAL_DOUBLE(kd * 2, pid.getKd());
Testing values set for constructor should be separate to testing setters and getters.

2020-11-17 21:54 UTC, manchester-hyperloop commented on test/Pid_Test/Pid_Test.cpp
> +    TEST_ASSERT_EQUAL_DOUBLE(kd * 2, pid.getKd());
Setter and getter for each value should have unique test (test everything individually, not in one big clump).

2020-11-17 22:04 UTC, mblenczewski commented on include/Core/Pid.hpp
> +#ifndef CORE_PID_HPP
so the namespace should also be Dynamics::Pid ?

2020-11-17 22:06 UTC, mblenczewski commented on src/main.cpp
> +  }
That was part of my testing code, sure thing

2020-11-17 22:06 UTC, mblenczewski commented on src/main.cpp
> +
Again, testing code with my own arduino

2020-11-17 22:06 UTC, mblenczewski commented on src/main.cpp
> +#include "Core/Pid.hpp"
Testing code

2020-11-17 22:07 UTC, mblenczewski commented on src/main.cpp
> +Core::Pid pid = Core::Pid(pid_setpoint, kp, ki, kd);
Testing code

2020-11-17 22:07 UTC, mblenczewski commented on test/Pid_Test/Pid_Test.cpp
> +void test_pid_works(void)
Yeah sure

2020-11-17 22:07 UTC, mblenczewski commented on test/Pid_Test/Pid_Test.cpp
> +void test_pid_getters_and_setters(void)
Yeah sure

2020-11-17 22:10 UTC, mblenczewski commented on test/Pid_Test/Pid_Test.cpp
> +    TEST_ASSERT_EQUAL_DOUBLE(kd * 2, pid.getKd());
I dont think thats necessary. Doing so would introduce 8 test cases. Thats excessive, and unnecessary, since the above code establishes the same facts (the test will fail at the first assert, which means we have to fix something). The only thing with the above code is that it leads to further setter and getter faults being masked until the previous one is fixed. Imho thats fine. If you manage to mess up a setter and getter then you deserve to spend the extra ten seconds to wait to see you messed up another one :^). Doing separate test cases would bloat the test src file needlessly, and i dont think its useful at all. Please explain more

2020-11-17 22:10 UTC, mblenczewski commented on test/Pid_Test/Pid_Test.cpp
> +    TEST_ASSERT_EQUAL_DOUBLE(kd * 2, pid.getKd());
eh. sure. seems somewhat reasonable

2020-11-19 09:36 UTC, manchester-hyperloop commented on include/Core/Pid.hpp
> +#ifndef CORE_PID_HPP
Nahh, just Dynamics. Pid is the class.

2020-11-19 09:39 UTC, manchester-hyperloop approved these changes
Well done, looks great!

2020-11-19 09:39 UTC, manchester-hyperloop commented on include/Dynamics/Pid.hpp
> +typedef unsigned long __pid_time_t;
Nice! Wouldn't of thought to do this but pretty useful!

2020-11-19 09:39 UTC, merged